package co.embracejoy.accounting.keystone.infrastructure.web.admin;

import co.embracejoy.accounting.keystone.application.tenancy.TenantService;
import co.embracejoy.accounting.keystone.domain.shared.Result;
import co.embracejoy.accounting.keystone.domain.tenancy.Tenant;
import co.embracejoy.accounting.keystone.domain.tenancy.TenantError;
import co.embracejoy.accounting.keystone.domain.tenancy.TenantId;
import co.embracejoy.accounting.keystone.infrastructure.web.ResultMapper;
import co.embracejoy.accounting.keystone.infrastructure.web.admin.dto.CreateTenantRequest;
import co.embracejoy.accounting.keystone.infrastructure.web.admin.dto.TenantResponse;
import io.swagger.v3.oas.annotations.Operation;
import jakarta.validation.Valid;
import java.net.URI;
import java.util.List;
import java.util.UUID;
import org.springframework.http.MediaType;
import org.springframework.http.ProblemDetail;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/admin/tenants")
public class TenantController {

  private final TenantService service;

  public TenantController(TenantService service) {
    this.service = service;
  }

  @PostMapping
  @PreAuthorize("hasRole('PLATFORM_ADMIN')")
  @Operation(
      summary = "Create a tenant",
      description =
          "Creates a new tenant. The tenant id is a UUID v7 generated by the server; the body"
              + " carries only the tenant display name. Returns 201 with a Location header"
              + " pointing at the new tenant.")
  public ResponseEntity<?> create(@Valid @RequestBody CreateTenantRequest req) {
    Result<Tenant, TenantError> r = service.create(req.name());
    return r.fold(
        t ->
            ResponseEntity.created(URI.create("/admin/tenants/" + t.id().value()))
                .body(TenantResponse.of(t)),
        this::error);
  }

  @GetMapping
  @PreAuthorize("hasRole('PLATFORM_ADMIN')")
  @Operation(
      summary = "List all tenants",
      description = "Returns every tenant, active and deactivated, ordered by creation time.")
  public List<TenantResponse> list() {
    return service.findAll().stream().map(TenantResponse::of).toList();
  }

  @GetMapping("/{id}")
  @PreAuthorize("hasRole('PLATFORM_ADMIN')")
  @Operation(
      summary = "Fetch one tenant by id",
      description =
          "Returns the tenant with the given UUID, or 404 if no such tenant exists. A malformed"
              + " id also returns 404.")
  public ResponseEntity<?> get(@PathVariable String id) {
    TenantId tenantId;
    try {
      tenantId = new TenantId(UUID.fromString(id));
    } catch (IllegalArgumentException e) {
      return notFoundByRawId(id);
    }
    return service
        .findById(tenantId)
        .<ResponseEntity<?>>map(t -> ResponseEntity.ok(TenantResponse.of(t)))
        .orElseGet(() -> error(new TenantError.NotFound(tenantId)));
  }

  @DeleteMapping("/{id}")
  @PreAuthorize("hasRole('PLATFORM_ADMIN')")
  @Operation(
      summary = "Deactivate a tenant",
      description =
          "Soft-deletes the tenant by setting its deactivatedAt timestamp. Idempotent: re-deleting"
              + " an already-deactivated tenant returns the current deactivated tenant with 200.")
  public ResponseEntity<?> delete(@PathVariable String id) {
    TenantId tenantId;
    try {
      tenantId = new TenantId(UUID.fromString(id));
    } catch (IllegalArgumentException e) {
      return notFoundByRawId(id);
    }
    Result<Tenant, TenantError> r = service.deactivate(tenantId);
    return r.fold(
        t -> ResponseEntity.ok(TenantResponse.of(t)), err -> handleDeleteError(tenantId, err));
  }

  private ResponseEntity<?> handleDeleteError(TenantId tenantId, TenantError err) {
    if (err instanceof TenantError.Deactivated) {
      return service
          .findById(tenantId)
          .<ResponseEntity<?>>map(t -> ResponseEntity.ok(TenantResponse.of(t)))
          .orElseGet(() -> error(new TenantError.NotFound(tenantId)));
    }
    return error(err);
  }

  private ResponseEntity<ProblemDetail> error(TenantError err) {
    ProblemDetail pd = ResultMapper.toProblemDetail(err);
    return ResponseEntity.status(pd.getStatus())
        .contentType(MediaType.parseMediaType("application/problem+json"))
        .body(pd);
  }

  private ResponseEntity<ProblemDetail> notFoundByRawId(String rawId) {
    ProblemDetail pd = ResultMapper.tenantNotFoundByRawId(rawId);
    return ResponseEntity.status(pd.getStatus())
        .contentType(MediaType.parseMediaType("application/problem+json"))
        .body(pd);
  }
}
